language: android
jdk: oraclejdk7

branches:
  only:
  - master

android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.1
  - android-26
  - extra-android-m2repository
  licenses:
  - android-sdk-license-.+
  - google-gdk-license-.+

script:
  - ./gradlew clean build
