language: android
jdk: oraclejdk7

branches:
  only:
  - master

android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.2
  - android-23
  - extra
  licenses:
  - android-sdk-license-.+
  - google-gdk-license-.+

script:
  - ./gradlew clean build
